/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aug3.storage.passage.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Storage implements org.apache.thrift.TEnum {
  S3(0),
  HAFS(1);

  private final int value;

  private Storage(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Storage findByValue(int value) { 
    switch (value) {
      case 0:
        return S3;
      case 1:
        return HAFS;
      default:
        return null;
    }
  }
}
